In [9]:
from sklearn import preprocessing
from sklearn.cross_validation import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC
import pandas as pd
import numpy as np

In [16]:
df = pd.read_csv("data/datasetindividual.csv")

In [13]:
df

dist1     dist2     dist3     dist4     dist5    canon1    canon2  \
0  -0.560804 -0.321643 -1.301336  0.433638 -1.100084  0.674457  0.586279   
1   1.433003 -0.776422 -0.151928 -0.629632 -0.697864  0.584947 -0.911667   
2  -0.625795 -0.817783 -0.226339 -0.029017 -1.027741 -1.012668 -0.812414   
3  -0.650544 -1.378405 -0.386753 -0.408018 -0.296151 -0.991856 -0.855828   
4   0.764635 -0.280414 -1.514379 -1.002147  0.584626  2.518236  0.744003   
5   1.196305  0.663804 -0.405317  1.398334 -0.718392  0.944484  0.976282   
6  -0.593289  2.428052 -0.078737 -0.528133 -0.949377 -0.874096  1.346369   
7   1.340261 -0.519532  0.857256 -0.920495 -1.243251  0.820209 -0.941799   
8  -1.110800 -1.066369  0.577315 -0.795709  1.090754  0.100520 -0.108175   
9  -0.583280 -0.196552 -0.696176 -1.401309  0.121696 -0.753697 -0.661074   
10 -1.266589 -0.678401  0.400141  0.198106 -1.174882 -1.132927 -1.145955   
11  1.244970 -0.569605 -1.288529 -0.991708  0.987164  1.327247  0.534660   
12 -0.385003 -1.152862 -1.476323 -0.991708 -1.032423 -1.033928 -0.544137   
13 -0.275624 -0.220246 -1.489148  1.880164 -0.706751 -0.890009 -0.959316   
14  0.270239 -0.431554 -0.058389 -0.664407 -0.507136  0.221268  0.512317   
15 -1.656680 -0.824065  0.628264  0.288017 -1.394828 -0.941431 -1.182920   
16 -0.774589  0.245690 -0.282671 -0.799065 -0.541117 -1.036509 -0.308321   
17  1.590291  0.095852 -0.765895 -1.120930  0.079755  2.630921 -0.030048   
18 -0.955735  0.829192 -1.310285 -0.320907 -0.294998  0.606864  0.673981   
19 -1.058677  0.710008 -0.354205 -1.054456  0.238284 -0.294693  1.777548   
20  0.338272 -0.365616 -0.098316 -0.825145 -0.463309  1.939908  0.489118   
21  0.128531 -1.156854 -0.069917  0.173852 -0.065557 -0.268735 -1.066178   
22  0.431188  1.423070 -0.413614 -0.149320 -0.884460  0.741140  1.920544   
23 -0.331658 -0.634276 -0.563741 -1.243251 -0.352479 -0.918533 -1.294815   
24 -0.085456  0.886556 -0.372755 -1.603369 -1.126395 -0.916097  0.146018   
25 -0.495870 -0.679678 -0.214214 -0.261793 -0.905944 -0.811858 -0.918102   
26  0.394523 -1.286677  0.123050 -0.994333 -0.255998 -0.561980 -1.327838   
27  0.093961 -0.602188 -0.252667 -1.820589  0.038139 -0.428572 -1.190725   
28 -0.067955 -0.918953  0.067290 -0.620073 -0.230620 -0.753931 -1.166036   
29  1.143859 -0.127181 -0.301041  0.200184  0.778602  0.007339 -0.458606   
30  1.087776  1.373507  0.828137 -0.267700  0.151900 -0.485012  0.774082   
31  1.085782 -0.078052 -0.440025  0.918621 -0.441894 -0.288476 -1.326548   
32 -0.465196 -0.424159  0.404660 -0.578773  0.813579  0.504634  0.907735   
33 -0.502797  1.382239  0.000596 -0.507577  0.092225  1.029033  1.239754   
34  0.714786 -0.051436  0.113771  0.162003  0.037883  0.571551 -0.334073   
35  0.270538 -0.746485 -1.384333  0.774103  0.000822 -0.687111 -0.963119   
36 -0.251966 -0.163289  0.680682 -0.599700  0.043096  0.322255 -0.013333   
37  0.659991  2.362139  0.605263  0.334794  0.443027  0.576766  1.020778   
38  2.915245 -0.650762 -0.014236 -0.151218  0.342673  1.677576 -0.725682   
39 -0.521964  1.223687  0.007311 -0.975446 -0.809662  0.502163  1.024563   
40 -0.349361  1.113952 -0.115289 -0.880390 -1.069656 -0.827736  0.480398   
41 -0.967945 -1.068430 -0.406344 -0.087707 -0.652803 -1.014554 -1.103382   
42 -0.947942 -0.647595 -0.772811 -0.705190 -0.422963 -1.203240 -0.858728   
43 -0.757278 -0.103767  0.573571 -1.376295 -0.762422 -1.071049 -1.266243   
44  1.307222 -0.464360 -0.312663 -0.701079 -1.244929  2.777819 -0.298898   
45  1.252824 -0.908242 -0.029813 -1.088694 -0.711251  0.033793 -1.188116   
46 -1.096002 -0.244844  0.166857 -0.500983 -0.507839 -1.258832 -0.753528   
47 -1.063066  1.769076 -0.405060 -0.680675  0.040758  0.035548  1.601979   
48 -0.279866  0.398613  0.200705 -0.271442 -0.677100 -0.736778 -0.207731   
49  0.512345 -0.866954  0.159897 -1.097842 -0.083209  0.201686 -0.996745   
50 -0.314308  0.515564 -0.660499  0.068704 -1.519638 -1.190794  0.207539   
51 -1.395159 -1.146359 -0.864079  0.243189 -1.104725 -1

In [3]:
# best_model_sensitivity_index = 0  # best model that can classify man  (+1)
# best_model_specificity_index = 0  # best model that can classify zone (-1)
from sklearn.svm import SVC
import pandas as pd
import numpy as np
from metrics.evaluation import cross_validate_stratify

df = pd.read_csv("data/dataset.csv")


X = np.matrix(df.iloc[:, range(14)].values)
y = df.iloc[:, 14].values

svm = SVC(class_weight='balanced')
result = cross_validate_stratify(svm, X, y, fold=10)
print ""

acc = result["acc_model"]
sens = result["sens_model"]
spec = result["spec_model"]

print "####### TRAIN ACC #######"
print acc[1][3]

print "####### TRAIN SENS #######"
print sens[1][3]

print "####### TRAIN SPEC #######"
print spec[1][3]

print ""

print "####### TEST ACC #######"
print acc[2][3]

print "####### TEST SENS #######"
print sens[2][3]

print "####### TEST SPEC #######"
print spec[2][3]



####### TRAIN ACC #######
[[ 8  1]
 [ 1 38]]
####### TRAIN SENS #######
[[ 8  1]
 [ 1 38]]
####### TRAIN SPEC #######
[[ 9  0]
 [ 6 33]]

####### TEST ACC #######
[[18  1]
 [ 5 83]]
####### TEST SENS #######
[[18  1]
 [ 5 83]]
####### TEST SPEC #######
[[18  1]
 [ 5 83]]
