In [1]:
from metrics.evaluation import cross_validate_stratify, present_metrics
from sklearn import preprocessing
from sklearn.cross_validation import StratifiedShuffleSplit, StratifiedKFold
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC
from sklearn.svm import SVC

import pandas as pd
import numpy as np
import pandas as pd
import numpy as np

using it all together

In [2]:
label = pd.read_csv("data/dataset.csv")
labely = label.iloc[:, 13].values
sss = StratifiedShuffleSplit(labely, n_iter=1, test_size=0.4, random_state=0)

for train_index, test_index in sss:
    train_indices= train_index
    test_indices = test_index
skf = StratifiedKFold(labely[train_indices], n_folds=3)

DATA SET INDIVIDUAL

In [3]:
df = pd.read_csv("data/datasetindividual.csv")

X = np.matrix(df.iloc[:, range(0, 45)].values)
y = df.iloc[:, 45].values

svm = SVC(class_weight='balanced', probability=True)

result = cross_validate_stratify(svm, X[train_indices], X[test_indices], y[train_indices], y[test_indices], skf)
print ""

acci_all = result["acc_model"]
sensi_all = result["sens_model"]
speci_all = result["spec_model"]

present_metrics(acci_all, sensi_all, speci_all)


####### TRAIN ACC #######
ACCURACY: 1.0
SENSITIVITY: 1.0
SPECIFICITY: 1.0
AUROC: 1.0
[[43  0]
 [ 0 10]]
####### TRAIN SENS #######
ACCURACY: 0.981481481481
SENSITIVITY: 1.0
SPECIFICITY: 0.977272727273
AUROC: 1.0
[[43  1]
 [ 0 10]]
####### TRAIN SPEC #######
ACCURACY: 1.0
SENSITIVITY: 1.0
SPECIFICITY: 1.0
AUROC: 1.0
[[43  0]
 [ 0 10]]

####### TEST ACC #######
ACCURACY: 0.897196261682
SENSITIVITY: 0.736842105263
SPECIFICITY: 0.931818181818
AUROC: 0.931220095694
[[82  6]
 [ 5 14]]
####### TEST SENS #######
ACCURACY: 0.897196261682
SENSITIVITY: 0.736842105263
SPECIFICITY: 0.931818181818
AUROC: 0.931220095694
[[82  6]
 [ 5 14]]
####### TEST SPEC #######
ACCURACY: 0.897196261682
SENSITIVITY: 0.736842105263
SPECIFICITY: 0.931818181818
AUROC: 0.931220095694
[[82  6]
 [ 5 14]]


DATA SET INDIVIDUAL NO VORONOI TESSELLATION

In [4]:
df = pd.read_csv("data/datasetindividual.csv")

X = np.matrix(df.iloc[:, range(0, 45)].values)
y = df.iloc[:, 45].values

svm = SVC(class_weight='balanced', probability=True)

result = cross_validate_stratify(svm, X[train_indices], X[test_indices], y[train_indices], y[test_indices], skf)
print ""

acci_novoronoi = result["acc_model"]
sensi_novoronoi = result["sens_model"]
speci_novoronoi = result["spec_model"]

present_metrics(acci_novoronoi, sensi_novoronoi, speci_novoronoi)


####### TRAIN ACC #######
ACCURACY: 1.0
SENSITIVITY: 1.0
SPECIFICITY: 1.0
AUROC: 1.0
[[43  0]
 [ 0 10]]
####### TRAIN SENS #######
ACCURACY: 0.981481481481
SENSITIVITY: 1.0
SPECIFICITY: 0.977272727273
AUROC: 1.0
[[43  1]
 [ 0 10]]
####### TRAIN SPEC #######
ACCURACY: 1.0
SENSITIVITY: 1.0
SPECIFICITY: 1.0
AUROC: 1.0
[[43  0]
 [ 0 10]]

####### TEST ACC #######
ACCURACY: 0.897196261682
SENSITIVITY: 0.736842105263
SPECIFICITY: 0.931818181818
AUROC: 0.931220095694
[[82  6]
 [ 5 14]]
####### TEST SENS #######
ACCURACY: 0.897196261682
SENSITIVITY: 0.736842105263
SPECIFICITY: 0.931818181818
AUROC: 0.931220095694
[[82  6]
 [ 5 14]]
####### TEST SPEC #######
ACCURACY: 0.897196261682
SENSITIVITY: 0.736842105263
SPECIFICITY: 0.931818181818
AUROC: 0.931220095694
[[82  6]
 [ 5 14]]


DATA SET ALL MEAN

In [5]:
df = pd.read_csv("data/dataset.csv")

X = np.matrix(df.iloc[:, range(0, 13)].values)
y = df.iloc[:, 13].values

svm = SVC(class_weight='balanced', probability=True)

result = cross_validate_stratify(svm, X[train_indices], X[test_indices], y[train_indices], y[test_indices], skf)
print ""

accm_all = result["acc_model"]
sensm_all = result["sens_model"]
specm_all = result["spec_model"]

present_metrics(accm_all, sensm_all, specm_all)


####### TRAIN ACC #######
ACCURACY: 0.981481481481
SENSITIVITY: 1.0
SPECIFICITY: 0.977272727273
AUROC: 0.997727272727
[[43  1]
 [ 0 10]]
####### TRAIN SENS #######
ACCURACY: 0.981481481481
SENSITIVITY: 1.0
SPECIFICITY: 0.977272727273
AUROC: 0.997727272727
[[43  1]
 [ 0 10]]
####### TRAIN SPEC #######
ACCURACY: 0.981481481481
SENSITIVITY: 1.0
SPECIFICITY: 0.977272727273
AUROC: 0.997727272727
[[43  1]
 [ 0 10]]

####### TEST ACC #######
ACCURACY: 0.897196261682
SENSITIVITY: 0.842105263158
SPECIFICITY: 0.909090909091
AUROC: 0.953947368421
[[80  8]
 [ 3 16]]
####### TEST SENS #######
ACCURACY: 0.897196261682
SENSITIVITY: 0.842105263158
SPECIFICITY: 0.909090909091
AUROC: 0.953947368421
[[80  8]
 [ 3 16]]
####### TEST SPEC #######
ACCURACY: 0.897196261682
SENSITIVITY: 0.842105263158
SPECIFICITY: 0.909090909091
AUROC: 0.953947368421
[[80  8]
 [ 3 16]]


DATA SET ALL MEAN NO VORONOI

In [6]:
df = pd.read_csv("data/dataset.csv")

X = np.matrix(df.iloc[:, range(0, 8)].values)
y = df.iloc[:, 13].values

svm = SVC(class_weight='balanced', probability=True)

result = cross_validate_stratify(svm, X[train_indices], X[test_indices], y[train_indices], y[test_indices], skf)
print ""

accm_novoronoi = result["acc_model"]
sensm_novoronoi = result["sens_model"]
specm_novoronoi = result["spec_model"]

present_metrics(accm_novoronoi, sensm_novoronoi, specm_novoronoi)


####### TRAIN ACC #######
ACCURACY: 0.924528301887
SENSITIVITY: 1.0
SPECIFICITY: 0.906976744186
AUROC: 1.0
[[39  4]
 [ 0 10]]
####### TRAIN SENS #######
ACCURACY: 0.907407407407
SENSITIVITY: 1.0
SPECIFICITY: 0.886363636364
AUROC: 0.993181818182
[[39  5]
 [ 0 10]]
####### TRAIN SPEC #######
ACCURACY: 0.924528301887
SENSITIVITY: 1.0
SPECIFICITY: 0.906976744186
AUROC: 1.0
[[39  4]
 [ 0 10]]

####### TEST ACC #######
ACCURACY: 0.869158878505
SENSITIVITY: 0.894736842105
SPECIFICITY: 0.863636363636
AUROC: 0.921650717703
[[76 12]
 [ 2 17]]
####### TEST SENS #######
ACCURACY: 0.869158878505
SENSITIVITY: 0.894736842105
SPECIFICITY: 0.863636363636
AUROC: 0.921650717703
[[76 12]
 [ 2 17]]
####### TEST SPEC #######
ACCURACY: 0.869158878505
SENSITIVITY: 0.894736842105
SPECIFICITY: 0.863636363636
AUROC: 0.921650717703
[[76 12]
 [ 2 17]]
