In [1]:
from metrics.evaluation import cross_validate_stratify, present_metrics
from sklearn import preprocessing
from sklearn.cross_validation import StratifiedShuffleSplit, StratifiedKFold
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC
from sklearn.svm import SVC

import pandas as pd
import numpy as np
import pandas as pd
import numpy as np

using it all together

In [2]:
label = pd.read_csv("data/dataset.csv")
labely = label.iloc[:, 13].values
sss = StratifiedShuffleSplit(labely, n_iter=1, test_size=0.4, random_state=0)

for train_index, test_index in sss:
    train_indices= train_index
    test_indices = test_index
skf = StratifiedKFold(labely[train_indices], n_folds=3)

DATA SET INDIVIDUAL

In [3]:
df = pd.read_csv("data/datasetindividual.csv")

X = np.matrix(df.iloc[:, range(0, 45)].values)
y = df.iloc[:, 45].values

svm = SVC(class_weight='balanced', probability=True)

result = cross_validate_stratify(svm, X[train_indices], X[test_indices], y[train_indices], y[test_indices], skf)
print ""

gmeani_all = result["gmean_model"]

present_metrics(gmeani_all, "GMEAN")


####### TRAIN GMEAN #######
SENSITIVITY: 1.0
SPECIFICITY: 1.0
MATTHEWS CORR COEF: 1.0
GMEAN: 1.0
[[43  0]
 [ 0 10]]

####### TEST GMEAN #######
SENSITIVITY: 0.736842105263
SPECIFICITY: 0.931818181818
MATTHEWS CORR COEF: 0.655464300192
GMEAN: 0.828615031733
[[82  6]
 [ 5 14]]


DATA SET INDIVIDUAL NO VORONOI TESSELLATION

In [4]:
df = pd.read_csv("data/datasetindividual.csv")

X = np.matrix(df.iloc[:, range(0, 45)].values)
y = df.iloc[:, 45].values

svm = SVC(class_weight='balanced', probability=True)

result = cross_validate_stratify(svm, X[train_indices], X[test_indices], y[train_indices], y[test_indices], skf)
print ""

gmeani_novoronoi = result["gmean_model"]
present_metrics(gmeani_novoronoi, "GMEAN")


####### TRAIN GMEAN #######
SENSITIVITY: 1.0
SPECIFICITY: 1.0
MATTHEWS CORR COEF: 1.0
GMEAN: 1.0
[[43  0]
 [ 0 10]]

####### TEST GMEAN #######
SENSITIVITY: 0.736842105263
SPECIFICITY: 0.931818181818
MATTHEWS CORR COEF: 0.655464300192
GMEAN: 0.828615031733
[[82  6]
 [ 5 14]]


DATA SET ALL MEAN

In [5]:
df = pd.read_csv("data/dataset.csv")

X = np.matrix(df.iloc[:, range(0, 13)].values)
y = df.iloc[:, 13].values

svm = SVC(class_weight='balanced', probability=True)

result = cross_validate_stratify(svm, X[train_indices], X[test_indices], y[train_indices], y[test_indices], skf)
print ""

gmeanm_all = result["gmean_model"]

present_metrics(gmeanm_all, "GMEAN")


####### TRAIN GMEAN #######
SENSITIVITY: 1.0
SPECIFICITY: 0.977272727273
MATTHEWS CORR COEF: 0.94256551606
GMEAN: 0.988571053224
[[43  1]
 [ 0 10]]

####### TEST GMEAN #######
SENSITIVITY: 0.842105263158
SPECIFICITY: 0.909090909091
MATTHEWS CORR COEF: 0.688219281399
GMEAN: 0.87495727852
[[80  8]
 [ 3 16]]


DATA SET ALL MEAN NO VORONOI

In [6]:
df = pd.read_csv("data/dataset.csv")

X = np.matrix(df.iloc[:, range(0, 8)].values)
y = df.iloc[:, 13].values

svm = SVC(class_weight='balanced', probability=True)

result = cross_validate_stratify(svm, X[train_indices], X[test_indices], y[train_indices], y[test_indices], skf)
print ""

gmeanm_novoronoi = result["gmean_model"]

present_metrics(gmeanm_novoronoi, "GMEAN")


####### TRAIN GMEAN #######
SENSITIVITY: 1.0
SPECIFICITY: 0.906976744186
MATTHEWS CORR COEF: 0.804885415175
GMEAN: 0.952353266486
[[39  4]
 [ 0 10]]

####### TEST GMEAN #######
SENSITIVITY: 0.894736842105
SPECIFICITY: 0.863636363636
MATTHEWS CORR COEF: 0.652010840824
GMEAN: 0.879049072992
[[76 12]
 [ 2 17]]
