In [1]:
from sklearn import preprocessing
from sklearn.cross_validation import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("data/dataset.csv")

In [3]:
# best_model_sensitivity_index = 0  # best model that can classify man  (+1)
# best_model_specificity_index = 0  # best model that can classify zone (-1)
from sklearn.svm import SVC
import pandas as pd
import numpy as np
from metrics.evaluation import cross_validate_stratify

df = pd.read_csv("data/dataset.csv")


X = np.matrix(df.iloc[:, range(14)].values)
y = df.iloc[:, 14].values

svm = SVC(class_weight='balanced')
result = cross_validate_stratify(svm, X, y, fold=10)
print ""

acc = result["acc_model"]
sens = result["sens_model"]
spec = result["spec_model"]

print "####### TRAIN ACC #######"
print acc[1][3]

print "####### TRAIN SENS #######"
print sens[1][3]

print "####### TRAIN SPEC #######"
print spec[1][3]

print ""

print "####### TEST ACC #######"
print acc[2][3]

print "####### TEST SENS #######"
print sens[2][3]

print "####### TEST SPEC #######"
print spec[2][3]



####### TRAIN ACC #######
[[ 8  1]
 [ 1 38]]
####### TRAIN SENS #######
[[ 8  1]
 [ 1 38]]
####### TRAIN SPEC #######
[[ 9  0]
 [ 6 33]]

####### TEST ACC #######
[[18  1]
 [ 5 83]]
####### TEST SENS #######
[[18  1]
 [ 5 83]]
####### TEST SPEC #######
[[18  1]
 [ 5 83]]
