In [7]:
from metrics.evaluation import cross_validate_stratify, present_metrics
from sklearn import preprocessing
from sklearn.cross_validation import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC
from sklearn.svm import SVC

import pandas as pd
import numpy as np
import pandas as pd
import numpy as np

using it all together

In [17]:
df = pd.read_csv("data/dataset.csv")
df.iloc[:, range(0, 13)]

distance   "canonical distance"   "distance - canonical"   "entropy"  \
0  -0.983019               0.564283                -0.340673    0.288474   
1  -0.319713              -0.904908                -0.495963   -0.161171   
2  -0.953258              -1.240144                -0.919362   -0.489528   
3  -1.099139              -1.172301                -1.309496   -0.550341   
4  -0.500711               0.940069                 0.076480   -0.667629   
5   0.723809               1.007187                 1.245194    1.210475   
6   0.178498              -0.541315                -0.137082   -0.189029   
7  -0.196583              -0.814239                -0.482927   -0.883002   
8  -0.457147               0.727244                 0.125580    1.122143   
9  -0.929184              -1.095104                -1.060676   -0.377397   
10 -0.874459              -1.282370                -1.131191   -1.463576   
11 -0.230619               0.594464                 0.278351   -0.211325   
12 -1.747619              -1.272795                -1.607543   -1.331828   
13 -0.295643              -0.667684                -0.383416   -1.828928   
14 -0.488843               0.653452                 0.045025    0.539402   
15 -1.025814              -1.109293                -1.265925   -1.977380   
16 -0.714254              -0.879159                -0.799678   -0.389686   
17 -0.047118               0.969415                 0.218519   -1.249993   
18 -0.661391               0.735806                -0.319704   -0.323480   
19 -0.475405               0.901137                 0.191455   -0.540526   
20 -0.493975               0.937497                 0.036748   -1.035905   
21 -0.377354              -0.767488                -0.558167   -0.197130   
22  0.176923               0.921075                 0.866108    0.671529   
23 -1.075223              -1.366843                -1.315581   -1.753268   
24 -0.749389              -0.956600                -0.786502   -1.217566   
25 -0.890477              -1.139524                -1.091800   -0.513696   
26 -0.728526              -1.092756                -0.593922    0.308158   
27 -0.874945              -1.202113                -1.008951   -0.952394   
28 -0.629165              -1.336630                -0.971110   -1.565973   
29  0.563502              -0.196071                 0.585831    1.641233   
30  1.116206              -0.129817                 0.536914    1.151492   
31  0.333976              -0.731821                -0.178119   -1.244028   
32 -0.086496               0.947737                 0.292077   -0.452734   
33  0.211931               1.046710                 0.579139    1.225660   
34  0.322732              -0.289336                 0.003389    0.731197   
35 -0.401276              -1.125405                -0.845821   -0.962479   
36 -0.097950               0.760452                 0.495471    0.564618   
37  1.569773               0.194057                 1.174782    2.252011   
38  0.782591              -0.315066                 0.352142    0.369825   
39 -0.319107               0.750861                 0.153965   -0.126660   
40 -0.402806              -0.781468                -0.939905   -0.298463   
41 -1.111084              -1.213572                -1.222206   -0.726128   
42 -1.199287              -1.403525                -1.223656   -2.245838   
43 -0.816790              -1.231231                -1.313237   -1.773275   
44 -0.512376               0.789136                -0.280251   -0.446118   
45 -0.544855              -1.020799                -0.865743   -0.729127   
46 -0.739160              -1.286383                -1.069411   -1.412612   
47 -0.042458               0.986401                 0.386250    0.115826   
48 -0.199977              -0.764305                -0.411174    0.298784   
49 -0.495476              -0.895193                -0.747387   -0.153072   
50 -0.638155              -0.725273                -0.510781   -1.550308   
51 -1.482453              -1.396715                -

In [4]:
# best_model_sensitivity_index = 0  # best model that can classify man  (+1)
# best_model_specificity_index = 0  # best model that can classify zone (-1)

df = pd.read_csv("data/dataset.csv")

X = np.matrix(df.iloc[:, range(0, 13)].values)
y = df.iloc[:, 13].values

svm = SVC(class_weight='balanced')

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4,
                                                        stratify=y)

result = cross_validate_stratify(svm, X_train, X_test, y_train, y_test, fold=10)
print ""

acc_allmean = result["acc_model"]
sens_allmean = result["sens_model"]
spec_allmean = result["spec_model"]

present_metrics(acc_allmean, sens_allmean, spec_allmean)


####### TRAIN ACC #######
ACCURACY: 1.0
SENSITIVITY: 1.0
SPECIFICITY: 1.0
[[ 9  0]
 [ 0 39]]
####### TRAIN SENS #######
ACCURACY: 1.0
SENSITIVITY: 1.0
SPECIFICITY: 1.0
[[ 9  0]
 [ 0 39]]
####### TRAIN SPEC #######
ACCURACY: 0.9375
SENSITIVITY: 0.923076923077
SPECIFICITY: 1.0
[[ 9  0]
 [ 3 36]]

####### TEST ACC #######
ACCURACY: 0.822429906542
SENSITIVITY: 0.840909090909
SPECIFICITY: 0.736842105263
[[14  5]
 [14 74]]
####### TEST SENS #######
ACCURACY: 0.822429906542
SENSITIVITY: 0.840909090909
SPECIFICITY: 0.736842105263
[[14  5]
 [14 74]]
####### TEST SPEC #######
ACCURACY: 0.822429906542
SENSITIVITY: 0.840909090909
SPECIFICITY: 0.736842105263
[[14  5]
 [14 74]]


In [ ]:
# best_model_sensitivity_index = 0  # best model that can classify man  (+1)
# best_model_specificity_index = 0  # best model that can classify zone (-1)

df = pd.read_csv("data/datasetindividual.csv")


X = np.matrix(df.iloc[:, range(0, 45)].values)
y = df.iloc[:, 45].values

svm = SVC(class_weight='balanced')

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4,
                                                        stratify=y)

result = cross_validate_stratify(svm, X_train, X_test, y_train, y_test, fold=10)
print ""

acc_allmean = result["acc_model"]
sens_allmean = result["sens_model"]
spec_allmean = result["spec_model"]

present_metrics(acc_allmean, sens_allmean, spec_allmean)